# Copyright 2026 Synthicsoft Labs LLC
# Licensed under the Apache License, Version 2.0.
[package]
name = "bowserd"
version.workspace = true
edition.workspace = true
license.workspace = true

authors.workspace = true

[dependencies]
bowser-core = { path = "../bowser-core" }
turtle = { path = "../turtle" }
koopa = { path = "../koopa" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
